services:
  db.dev:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - network_name
    env_file:
      - .env
    volumes:
      - ./sql_populate.sql:/opt/sql_populate.sql

  app.dev:
    user: "${UID}:${GID}"
    image: node:22
    working_dir: /app
    ports:
      - "${GRAPHQL_PORT:-13000}:${GRAPHQL_PORT:-13000}"
    volumes:
      - ./app:/app
    depends_on:
      - db.dev
    command: /bin/bash -c "npm install && npx sequelize db:migrate && npm run dev"
    env_file:
      - .env
    networks:
      - network_name

  frontend.dev:
    user: "${UID}:${GID}"
    image: node:22
    working_dir: /app
    ports:
      - "${FRONTEND_PORT:-8080}:8080"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: /bin/bash -c "npm install && npm run dev -- --host 0.0.0.0 --port 8080"
    env_file:
      - .env
    environment:
      - VITE_GRAPHQL_ENDPOINT=http://localhost:${GRAPHQL_PORT:-13000}/graphql
    networks:
      - network_name
    depends_on:
      - app.dev

networks:
  network_name:
    driver: bridge

volumes:
  frontend_node_modules:
